apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-lab-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vaiz1982/k8s-lab_defaultOne.git
    targetRevision: main
    path: k8s-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
