apiVersion: v1
kind: Pod
metadata:
  name: app-1-pod
  namespace: dev
  labels:
    env: dev     #app: app-1  before must mach with selector! 
spec:
  containers:
    - name: web-server-1
      image: nginx:alpine
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      
---

apiVersion: v1
kind: Service
metadata:
  name: app-1-svc      # the Service's own name
  namespace: dev        # lives in the "dev" namespace, same as your pod
spec:
  selector:
    env: dev             # ← finds any pod with label "env: dev"
  ports:
    - port: 80           # the port the Service itself listens on
      targetPort: 80     # the port forwarded to on the pod's container


---
apiVersion: v1
kind: Pod
metadata:
  name: app-1-pod
  namespace: prod
  labels:
    env: prod      ##app: app-1  before must mach with selector!
spec:
  containers:
    - name: web-server-1
      image: nginx:alpine
      ports:
        - containerPort: 80



---

apiVersion: v1
kind: Service
metadata:
  name: app-1-svc      # the Service's own name
  namespace: prod        # lives in the "dev" namespace, same as your pod
spec:
  selector:
    env: prod             # ← finds any pod with label "env: dev"
  ports:
    - port: 80           # the port the Service itself listens on
      targetPort: 80     # the port forwarded to on the pod's container
